# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build & deploy
        run: |
          docker build -t monitor-app .
          
          echo "Stopping old container (if exists)..."
          docker rm -f monitor-app-container || true
          
          docker run -d \
            --name monitor-app-container \
            -e TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} \
            -e ALPHAVANTAGE_TOKEN=${{ secrets.ALPHAVANTAGE_TOKEN }} \
            -e TWELVEDATA_TOKEN=${{ secrets.TWELVEDATA_TOKEN }} \
            -v /home/homepi/tasks.json:/app/tasks.json monitor-app